import { type TQuestion } from '~/pages/CollectInfo/types/collectInfo';

export const TOTAL_STEPS = 5;

export const STEP_LABELS = [
  {
    title: '1. 라이프스타일',
    description: '당신의 일상은 어떻게 흘러가나요?',
  },
  {
    title: '2. 성향 파악',
    description: '당신의 스타일을 알고, 딱 맞는 대화를 설계할게요',
  },
  {
    title: '3. 취향 파악',
    description: '편하게 이야기할 수 있는 관심사와 취향을 알려주세요',
  },
  {
    title: '4. 가치관 파악',
    description: '조금 더 깊게, 나다운 대화를 위해',
  },
  {
    title: '5. 나에 대한 한 문장',
    description: '나를 가장 잘 나타내는 한 문장을 적어보세요',
  },
];

export const STEP_END_IDS = [7, 20, 27, 33, 34];

export const QUESTIONS: TQuestion[] = [
  {
    id: 1,
    type: 'select',
    title: '당신의 아침은 어떤 편인가요?',
    maxChoice: 1,
    options: [
      { label: '새벽 일찍 일어나 하루를 준비해요', value: '1' },
      { label: '자연스럽게 눈 떠지는 대로 시작해요', value: '2' },
      { label: '아침은 느긋하게, 여유가 중요해요', value: '3' },
      { label: '급하게 준비하느라 항상 정신없어요', value: '4' },
    ],
  },
  {
    id: 2,
    type: 'select',
    title: '하루를 어떤 방식으로 보내는 편인가요?',
    maxChoice: 1,
    options: [
      { label: '대부분 일정한 루틴에 따라 움직여요', value: '1' },
      { label: '해야 할 일을 중심으로 계획해서 움직여요', value: '2' },
      { label: '그날그날 흘러가는 대로 사는 편이에요', value: '3' },
      { label: '낮에는 주로 개인 시간이나 공부/작업을 해요', value: '4' },
      { label: '저녁엔 쉬거나 좋아하는 활동을 즐겨요', value: '5' },
    ],
  },
  {
    id: 3,
    type: 'select',
    title: '주말에는 보통 어떻게 보내세요?',
    maxChoice: 1,
    options: [
      { label: '주말엔 계획 없이 자유롭게 보내는 게 좋아요', value: '1' },
      { label: '친구들이나 가족과 시간을 보내는 걸 좋아해요', value: '2' },
      { label: '취미나 관심 있는 활동을 하며 보내요', value: '3' },
      { label: '주말은 완전히 집에서 쉬어요', value: '4' },
      { label: '일이나 공부가 밀려서 주말에도 여유가 없어요', value: '5' },
    ],
  },
  {
    id: 4,
    type: 'select',
    title: '몸을 움직이는 걸 좋아하는 편인가요?',
    maxChoice: 1,
    options: [
      { label: '규칙적으로 운동하거나 활동하는 걸 좋아해요', value: '1' },
      { label: '요즘은 헬스/요가 등을 꾸준히 하고 있어요', value: '2' },
      { label: '가벼운 산책이나 스트레칭 정도는 자주 해요', value: '3' },
      { label: '운동은 안 하지만 걷는 건 좋아해요', value: '4' },
      { label: '완전 집순이/집돌이예요, 활동은 최소한으로!', value: '5' },
    ],
  },
  {
    id: 5,
    type: 'select',
    title: '식사 시간, 어떤 스타일이세요?',
    maxChoice: 1,
    options: [
      { label: '혼밥도 잘 하지만 함께 먹는 걸 더 좋아해요', value: '1' },
      { label: '식사 시간엔 대화가 중요하다고 생각해요', value: '2' },
      { label: '가리는 거 없이 아무거나 잘 먹는 편이에요', value: '3' },
      { label: '입맛이 까다로운 편이에요', value: '4' },
      { label: '맛집 탐방이나 새로운 음식 도전을 좋아해요', value: '5' },
      { label: '익숙하고 편한 데서 조용히 먹는 게 좋아요', value: '6' },
    ],
  },
  {
    id: 6,
    type: 'select',
    title: '쉬는 날엔 어떤 콘텐츠를 즐기시나요?',
    maxChoice: 1,
    options: [
      { label: '넷플릭스, 유튜브 정주행이 기본이에요', value: '1' },
      { label: '책이나 팟캐스트로 조용히 시간을 보내요', value: '2' },
      { label: '좋아하는 콘텐츠 덕질하는 걸 즐겨요', value: '3' },
      { label: 'SNS나 밈 보면서 가볍게 웃는 게 좋아요', value: '4' },
      { label: '아무것도 안 하는 게 최고의 휴식이에요', value: '5' },
    ],
  },
  {
    id: 7,
    type: 'select',
    title: '당신은 어느 쪽이 더 편하신가요?',
    maxChoice: 1,
    options: [
      { label: '완전 아침형! 해 뜨기 전에 움직이는 스타일', value: '1' },
      { label: '대체로 아침형, 일찍 자고 일찍 일어나요', value: '2' },
      { label: '중간형! 늦게 자긴 하지만 아침 일정도 가능', value: '3' },
      { label: '거의 야행성이에요, 밤이 더 활발해요', value: '4' },
      { label: '아침도 밤도 별로… 그냥 피곤한 현대인입니다', value: '5' },
    ],
  },
  {
    id: 8,
    type: 'select',
    title: '인간관계에서 당신은 어떤 유형의 사람인가요?',
    maxChoice: 1,
    options: [
      { label: '혼자여도 지루하지 않고 잘 노는 편이에요', value: '1' },
      { label: '사람들과 어울릴 때 에너지를 얻는 스타일이에요', value: '2' },
      { label: '혼자 또는 소수의 사람들과 있는게 편해요', value: '3' },
      { label: '많은 사람들과 시끌벅적한 자리를 좋아해요', value: '4' },
      { label: '적당히 섞어서 균형을 맞추려 해요', value: '5' },
    ],
  },
  {
    id: 9,
    type: 'slider',
    title: '본인을 고른다면 더 가까운 쪽은?',
    minLabel: '내향적',
    maxLabel: '외향적',
    min: 0,
    max: 100,
    step: 1,
  },
  {
    id: 10,
    type: 'select',
    title: '소개팅 중 침묵이 흐르면, 당신은?',
    maxChoice: 1,
    options: [
      { label: '🗣️ 일단 뭔가라도 말해서 깨보려 해요', value: '1' },
      { label: '😅 웃으며 무언가 반응이라도 해요', value: '2' },
      { label: '🙃 속으로는 식은땀… 티는 안 내요', value: '3' },
      { label: '🧘‍♀️ 자연스럽게 흐를 때까지 기다리는 편이에요', value: '4' },
      { label: '🤔 그 순간을 관찰하며 상대를 살펴봐요', value: '5' },
    ],
  },
  {
    id: 11,
    type: 'select',
    title: '말이 꼬이거나 실수하면 어떻게 하세요?',
    maxChoice: 1,
    options: [
      { label: '😆 그냥 웃어넘기고 다시 말해요', value: '1' },
      { label: '😳 순간 얼어서 아무 말도 못 해요', value: '2' },
      { label: '🙃 혼자 머쓱해져요...', value: '3' },
      { label: '🧠 나만의 실수 회복 멘트를 써요', value: '4' },
      { label: '🆘 누가 좀 도와줬으면 좋겠어요', value: '5' },
    ],
  },
  {
    id: 12,
    type: 'select',
    title: '처음 만났을 때, 가장 중요하다고 생각하는 포인트',
    maxChoice: 1,
    options: [
      { label: '🌿 자연스럽고 편안한 분위기', value: '1' },
      { label: '💬️ 상대와 잘 통하는 대화', value: '2' },
      { label: '✨ 내 매력을 잘 보여주는 것', value: '3' },
      { label: '🎨 서로의 가치관이나 취향을 알아가는 것', value: '4' },
      { label: '⚡ 느낌이 통하는지 확인하는 것', value: '5' },
    ],
  },
  {
    id: 13,
    type: 'select',
    title: '나를 어필할 땐 이런 방식이 편해요!',
    maxChoice: 1,
    options: [
      { label: '재밌게 말하면서 웃기려고 해요', value: '1' },
      { label: '진지하게 내 이야기를 차분히 해요', value: '2' },
      { label: '질문을 많이 하면서 관심을 표현해요', value: '3' },
      { label: '자연스럽게 분위기를 리드해요', value: '4' },
      { label: '매력 어필이 어색해요', value: '5' },
    ],
  },
  {
    id: 14,
    type: 'select',
    title: '소개팅에서, 어떤 게 가장 먼저 궁금하세요?',
    maxChoice: 1,
    options: [
      { label: '취미 또는 평소 생활', value: '1' },
      { label: '어떤 가치관을 가진 사람인지', value: '2' },
      { label: '대화할 때 성향이나 태도', value: '3' },
      { label: '그냥 느낌이 잘 맞는지가 제일 중요해요', value: '4' },
      { label: '혹시 안 맞는 부분은 뭘까? (생활 리듬 등)', value: '5' },
    ],
  },
  {
    id: 15,
    type: 'select',
    title: '대화가 길어질 때 당신의 대처 방안은?',
    maxChoice: 1,
    options: [
      { label: '슬슬 주제 바꾸고 싶어져요', value: '1' },
      { label: '한 가지 주제에 깊게 이야기하는 걸 좋아해요', value: '2' },
      { label: '상대 분위기 보면서 조심스럽게 넘어가요', value: '3' },
      { label: '유머나 농담으로 전환해요', value: '4' },
      { label: '대화가 끊기면 그 타이밍에 넘겨요', value: '5' },
    ],
  },
  {
    id: 16,
    type: 'select',
    title: '어떤 유형의 유머를 선호하시나요?',
    maxChoice: 1,
    options: [
      { label: '가볍고 재치 있는 농담을 좋아해요', value: '1' },
      { label: '블랙 유머나 풍자적인 유머도 괜찮아요', value: '2' },
      { label: '상황에 맞는 유머, 자연스럽게 웃길 때가 좋아요', value: '3' },
      { label: '유머보다는 진지한 대화가 더 편해요', value: '4' },
    ],
  },
  {
    id: 17,
    type: 'select',
    title: '스트레스를 받을 땐 어떻게 푸시나요?',
    maxChoice: 1,
    options: [
      { label: '집에서 누워서 콘텐츠 보며 뒹굴거리기', value: '1' },
      { label: '멍 때리거나 숙면하기', value: '2' },
      { label: '친구와 수다 떨며 털어내는 편이에요', value: '3' },
      { label: '운동이나 산책 등 몸을 움직여서 푸는 편이에요', value: '4' },
      { label: '맛있는 걸 먹거나 소소한 쇼핑으로 풀어요', value: '5' },
    ],
  },
  {
    id: 18,
    type: 'select',
    title: '여행할 때 나는 이런 스타일이에요',
    maxChoice: 1,
    options: [
      { label: '계획을 꼼꼼히 짜고 알차게 움직이는 편이에요', value: '1' },
      { label: '느긋한 즉흥 여행을 더 좋아해요', value: '2' },
      { label: '자연, 한적한 장소에서 힐링하는 걸 선호해요', value: '3' },
      { label: '도시에서 먹고 마시고 구경하는 게 재밌어요', value: '4' },
      { label: '액티비티와 모험을 즐기는 여행을 좋아해요', value: '5' },
      { label: '여행을 즐기지 않는 편이에요', value: '6' },
    ],
  },
  {
    id: 19,
    type: 'select',
    title: '대화 중 어떤 스타일이 편한가요?',
    maxChoice: 1,
    options: [
      { label: '내가 주도하는 대화가 편해요', value: '1' },
      { label: '상대방이 리드해주는 스타일이 편해요', value: '2' },
      { label: '반응에 맞춰 대화를 이어가는 스타일이에요', value: '3' },
      { label: '가벼운 농담을 섞은 대화가 좋아요', value: '4' },
    ],
  },
  {
    id: 20,
    type: 'select',
    title: '대화 중 불편한 상황이 생기면 어떻게 하나요?',
    maxChoice: 1,
    options: [
      { label: '솔직하게 불편함을 이야기해요', value: '1' },
      { label: '대화를 피하거나 다른 주제로 돌려요', value: '2' },
      { label: '상대방에게 감정을 상하지 않게 표현해요', value: '3' },
      { label: '나중에 스스로 감정을 정리한 뒤 이야기해요', value: '4' },
      { label: '대화가 어렵다고 느껴지면 그냥 참아요', value: '5' },
    ],
  },
  {
    id: 21,
    type: 'multiple_choice',
    title: '다음 중 편하게 이야기할 수 있는 주제를 선택해주세요!',
    options: [
      {
        label: '영화 / 드라마',
        value: '1',
      },
      {
        label: '음악',
        value: '2',
      },
      {
        label: '음식 / 맛집',
        value: '3',
      },
      {
        label: '독서',
        value: '4',
      },
      {
        label: '가치관',
        value: '5',
      },
      {
        label: '철학적 토론',
        value: '6',
      },
      {
        label: '연애 경험',
        value: '7',
      },
      {
        label: '반려동물',
        value: '8',
      },
      {
        label: '운동',
        value: '9',
      },
      {
        label: '자기관리',
        value: '10',
      },
      {
        label: 'TMI',
        value: '11',
      },
      {
        label: '취미 / 관심사',
        value: '12',
      },
      {
        label: '일상 업무',
        value: '13',
      },
      {
        label: '패션',
        value: '14',
      },
      {
        label: '꿈과 목표',
        value: '15',
      },
      {
        label: '웃긴 이야기',
        value: '16',
      },
      {
        label: '문화 활동',
        value: '17',
      },
      {
        label: '직업',
        value: '18',
      },
      {
        label: '예술',
        value: '19',
      },
      {
        label: '가족 / 친밀한 관계',
        value: '20',
      },
      {
        label: '취미',
        value: '21',
      },
      {
        label: '환경 보호',
        value: '22',
      },
      {
        label: '뉴스',
        value: '23',
      },
      {
        label: '정치적 이슈',
        value: '24',
      },
      {
        label: '인생 계획',
        value: '25',
      },
      {
        label: '게임',
        value: '26',
      },
      {
        label: '애니메이션',
        value: '27',
      },
      {
        label: '건강 / 웰빙',
        value: '28',
      },
    ],
  },
  {
    id: 22,
    type: 'select',
    title: '반려동물과 함께하는 삶, 당신은 어떤가요?',
    maxChoice: 1,
    options: [
      { label: '강아지/고양이와 함께 살아가요', value: '1' },
      { label: '반려동물은 없지만, 좋아해요!', value: '2' },
      { label: '특이한 반려동물을 키우는 것에 관심이 있어요', value: '3' },
      { label: '동물을 별로 좋아하지 않아요', value: '4' },
    ],
  },
  {
    id: 23,
    type: 'select',
    title: '선호하는 주종이 어떻게 되나요?',
    maxChoice: 1,
    options: [
      { label: '가벼운 맥주를 좋아해요', value: '1' },
      { label: '소주 또는 소맥을 좋아해요', value: '2' },
      { label: '분위기 있는 와인을 좋아해요', value: '3' },
      { label: '위스키와 같은 양주를 좋아해요', value: '4' },
      { label: '술보다는 음료나 차를 즐겨요', value: '5' },
      { label: '술을 전혀 즐기지 않아요', value: '6' },
    ],
  },
  {
    id: 24,
    type: 'select',
    title: '술자리에서 어떤 스타일을 선호하시나요?',
    maxChoice: 1,
    options: [
      { label: '많은 사람과 즐겁게 술자리 갖는 걸 좋아해요', value: '1' },
      { label: '조용히 이야기 나누는 술자리를 좋아해요', value: '2' },
      { label: '혼자 술을 먹는 걸 좋아해요', value: '3' },
      { label: '술을 잘 못하지만 분위기는 좋아해요', value: '4' },
      { label: '술자리를 좋아하지 않아요', value: '5' },
    ],
  },
  {
    id: 25,
    type: 'select',
    title: '당신이 자주 찾는 미디어는 무엇인가요?',
    maxChoice: 1,
    options: [
      { label: '뉴스, 사회나 경제에 대한 관심 많아요', value: '1' },
      { label: '유튜브, 다양한 채널을 즐겨봐요', value: '2' },
      { label: 'SNS, 다양한 트렌드를 따라가요', value: '3' },
      { label: '아티클, 깊이 있는 정보나 글을 자주 찾아요', value: '4' },
      { label: '미디어 콘텐츠를 즐겨보지 않아요', value: '5' },
    ],
  },
  {
    id: 26,
    type: 'select',
    title: '첫 만남에서 어떤 대화가 편하신가요?',
    maxChoice: 1,
    options: [
      { label: '자기소개와 일상 얘기', value: '1' },
      { label: '취미나 관심사 이야기', value: '2' },
      { label: '가벼운 농담과 유머', value: '3' },
      { label: '가치관이나 철학적 대화', value: '4' },
    ],
  },
  {
    id: 27,
    type: 'select',
    title: '새로운 생각을 떠올리고 표현하는 걸 즐기시나요?',
    maxChoice: 1,
    options: [
      { label: '번뜩이는 아이디어를 떠올리는 걸 좋아해요', value: '1' },
      { label: '창의적인 작업에 몰입하는 걸 좋아해요', value: '2' },
      { label: '실용적인 쪽을 더 선호해요', value: '3' },
      { label: '안정적이고 체계적인 게 편해요', value: '4' },
    ],
  },
  {
    id: 28,
    type: 'select',
    title: '당신이 소중하게 여기는 가치는 무엇인가요?',
    maxChoice: 1,
    options: [
      { label: '정직, 거짓되지 않은 올곧음을 중요히 여겨요', value: '1' },
      { label: '자유, 나만의 시간을 소중히 여겨요', value: '2' },
      { label: '협력, 함께 이루는 것에 가치를 둬요', value: '3' },
      { label: '사랑, 배려하고 사랑하는 것이 중요해요', value: '4' },
      { label: '성장, 끊임없이 발전하고 싶어요', value: '5' },
      { label: '안정, 편안한 일상을 중요하게 생각해요', value: '6' },
    ],
  },
  {
    id: 29,
    type: 'select',
    title: '피하고 싶은 민감한 대화 주제는 무엇인가요?',
    maxChoice: 1,
    options: [
      { label: '종교', value: '1' },
      { label: '정치', value: '2' },
      { label: '이전 연애 경험', value: '3' },
      { label: '가족 이야기', value: '4' },
      { label: '연봉', value: '5' },
      { label: '다른 소개팅 경험', value: '6' },
    ],
  },
  {
    id: 30,
    type: 'select',
    title: '타인을 대할 때 중요하게 여기는 태도는 무엇인가요?',
    maxChoice: 1,
    options: [
      { label: '존중, 서로의 입장을 이해하려고 노력해요', value: '1' },
      { label: '솔직함, 항상 진심으로 이야기해요', value: '2' },
      { label: '신뢰, 신뢰를 바탕으로 관계를 쌓아요', value: '3' },
      { label: '개방성, 다양한 생각을 받아들이려 해요', value: '4' },
      { label: '배려, 작은 것도 세심하게 신경 써요', value: '5' },
      { label: '공감, 마음을 나누는 걸 중요하게 생각해요', value: '6' },
    ],
  },
  {
    id: 31,
    type: 'select',
    title: '연애에서 중요하게 생각하는 요소는 무엇인가요?',
    maxChoice: 1,
    options: [
      { label: '유머 코드가 잘 맞는 것이 중요해요', value: '1' },
      { label: '공통의 관심사와 취미를 함께 즐기고 싶어요', value: '2' },
      { label: '미래에 대한 생각과 가치관을 나누고 싶어요', value: '3' },
      { label: '서로의 개인적인 공간을 존중하는 게 중요해요', value: '4' },
      { label: '스킨십과 같은 신체적인 접촉을 중요하게 여겨요', value: '5' },
      { label: '학벌, 경제적 상황, 조건 등을 중요하게 여겨요', value: '6' },
    ],
  },
  {
    id: 32,
    type: 'select',
    title: '당신의 인생에서 가장 중요한 목표는 무엇인가요?',
    maxChoice: 1,
    options: [
      { label: '개인적인 성장과 자기 개발', value: '1' },
      { label: '사랑하는 사람과 함께 행복한 삶', value: '2' },
      { label: '사회적 기여와 나누는 삶', value: '3' },
      { label: '물질적인 성공과 안정', value: '4' },
      { label: '명예와 존경을 받는 삶', value: '5' },
    ],
  },
  {
    id: 33,
    type: 'select',
    title: '중요하게 생각하는 사회적 가치는 무엇인가요?',
    maxChoice: 1,
    options: [
      { label: '환경 보호와 지속 가능성', value: '1' },
      { label: '모두가 공평한 기회를 제공받는 사회', value: '2' },
      { label: '모든 사람이 동등하게 대우받는 사회', value: '3' },
      { label: '기술의 혁신과 발전', value: '4' },
    ],
  },
  {
    id: 34,
    type: 'group_input',
    subQuestions: [
      {
        id: 1,
        title: '나의 성격을 한 문장으로 설명한다면?',
        placeholder: 'ex. 언제나 긍정적이고, 사람들과 쉽게 친해지는 성격이에요',
        required: false,
      },
      {
        id: 2,
        title: '내가 생각하는 나의 장점',
        placeholder: 'ex. 문제 해결능력이 뛰어나고 사람들을 돕는 걸 좋아해요',
        required: false,
      },
      {
        id: 3,
        title: '내가 생각하는 나의 단점',
        placeholder: 'ex. 가끔은 너무 신중해서 결정을 내리는데 시간이 걸려요',
        required: false,
      },
      {
        id: 4,
        title: '나는 어떤 사람과 잘 맞을 것 같나요?',
        placeholder: 'ex. 차분하고 이야기를 경청하는 사람과 잘 맞을 것 같아요',
        required: false,
      },
    ],
  },
];
