/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/debug/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug Token */
        get: operations["debug_token_debug_token_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 구글 OAuth 인증 시작 */
        get: operations["login_google_auth_google_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 구글 OAuth 콜백 */
        get: operations["callback_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 토큰 재발급 */
        post: operations["refresh_token_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 프로필 조회
         * @description - 로그인된 유저의 프로필을 조회합니다.
         *     - 프로필이 없으면 `profile` 필드는 null 로 내려갑니다.
         */
        get: operations["read_profile_users_me_profile_get"];
        put?: never;
        /**
         * 내 프로필 저장/업데이트
         * @description - 이름/나이/성별 등 기본 정보 + 직업/거주지역/MBTI/흡연여부를 한 번에 저장합니다.
         *     - region, mbti는 선택, smoking은 필수입니다.
         *     - 성공 시 전체 유저+프로필을 반환합니다.
         */
        post: operations["upsert_profile_users_me_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/survey/lifestyle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lifestyle with answers */
        get: operations["get_lifestyle_survey_lifestyle_get"];
        put?: never;
        /** Post Lifestyle */
        post: operations["post_lifestyle_survey_lifestyle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/survey/identify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Identify with answers */
        get: operations["get_identify_survey_identify_get"];
        put?: never;
        /** Post Identify */
        post: operations["post_identify_survey_identify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/survey/preference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preference with answers */
        get: operations["get_preference_survey_preference_get"];
        put?: never;
        /** Post Preference */
        post: operations["post_preference_survey_preference_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/survey/beliefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Beliefs with answers */
        get: operations["get_beliefs_survey_beliefs_get"];
        put?: never;
        /** Post Beliefs */
        post: operations["post_beliefs_survey_beliefs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/survey/essay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Essay(group_input) with answers */
        get: operations["get_group_input_survey_essay_get"];
        put?: never;
        /** Post Essay(group_input) answers */
        post: operations["post_group_input_survey_essay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 파트너 설문 질문 조회 */
        get: operations["get_questions_partners_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 파트너 조회 */
        get: operations["list_partners_partners_get"];
        put?: never;
        /** 새 파트너 등록 (최대 1개) */
        post: operations["post_partner_partners_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checklist/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 체크리스트 기본 항목 리스트 조회
         * @description 체크리스트에 사용할 기본 항목 텍스트 목록을 반환합니다.
         */
        get: operations["list_default_items_checklist_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 체크리스트 상태 조회
         * @description 현재 사용자가 체크한 항목의 상태를 반환합니다.
         */
        get: operations["get_checklist_checklist_get"];
        put?: never;
        /**
         * 체크/해제 토글
         * @description 특정 항목(item_id)에 대해 체크 또는 해제 상태를 업데이트합니다.
         */
        post: operations["toggle_check_checklist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 최근 파트너 일정 조회 */
        get: operations["get_schedule_schedules_get"];
        put?: never;
        /** 일정 등록 */
        post: operations["set_schedule_schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChecklistItemOut */
        ChecklistItemOut: {
            /** Id */
            id: number;
            /** Text */
            text: string;
        };
        /**
         * ChoiceAnswerIn
         * @example {
         *       "option_ids": [
         *         "1",
         *         "3",
         *         "5"
         *       ],
         *       "question_id": 21
         *     }
         */
        ChoiceAnswerIn: {
            /**
             * Question Id
             * @description QUESTION_DEFINITIONS 상의 id
             */
            question_id: number;
            /**
             * Option Id
             * @description 단일 선택 시
             */
            option_id?: string | null;
            /**
             * Option Ids
             * @description 복수 선택 시
             */
            option_ids?: string[] | null;
        };
        /** ChoiceAnswerList */
        ChoiceAnswerList: {
            /** Answers */
            answers: components["schemas"]["ChoiceAnswerIn"][];
        };
        /** GroupInputAnswerList */
        GroupInputAnswerList: {
            /** Answers */
            answers: components["schemas"]["SubQuestionAnswerIn"][];
        };
        /** GroupInputOut */
        GroupInputOut: {
            /**
             * Question Id
             * @default 34
             * @constant
             * @enum {integer}
             */
            question_id: 34;
            /** Answers */
            answers: components["schemas"]["SubQuestionOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NewPartnerIn */
        NewPartnerIn: {
            /** Answers */
            answers: components["schemas"]["ChoiceAnswerIn"][];
        };
        /** OptionOut */
        OptionOut: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** PartnerAnswerOut */
        PartnerAnswerOut: {
            /** Question Id */
            question_id: number;
            /** Option Id */
            option_id: string;
        };
        /** PartnerListOut */
        PartnerListOut: {
            /** Partners */
            partners: components["schemas"]["PartnerWithAnswersOut"][];
        };
        /** PartnerOut */
        PartnerOut: {
            /** Id */
            id: number;
        };
        /** PartnerWithAnswersOut */
        PartnerWithAnswersOut: {
            /** Id */
            id: number;
            /** Answers */
            answers: components["schemas"]["PartnerAnswerOut"][];
        };
        /**
         * ProfileIn
         * @example {
         *       "age": 28,
         *       "gender": "male",
         *       "job": "Developer",
         *       "mbti": "INTJ",
         *       "name": "홍길동",
         *       "region": "Seoul",
         *       "smoking": true
         *     }
         */
        ProfileIn: {
            /** Name */
            name: string;
            /** Age */
            age: number;
            /** Gender */
            gender: string;
            /**
             * Job
             * @description 직업
             */
            job?: string | null;
            /**
             * Region
             * @description 거주 지역 (선택)
             */
            region?: string | null;
            /**
             * Mbti
             * @description MBTI (선택)
             */
            mbti?: string | null;
            /**
             * Smoking
             * @description 흡연 여부 (필수)
             */
            smoking: boolean;
        };
        /** ProfileInitialOut */
        ProfileInitialOut: {
            /** Name */
            name: string;
            /** Age */
            age: number;
            /** Gender */
            gender: string;
            /** Job */
            job: string | null;
            /** Region */
            region: string | null;
            /** Mbti */
            mbti: string | null;
            /** Smoking */
            smoking: boolean;
        };
        /** QuestionList */
        QuestionList: components["schemas"]["QuestionOut"][];
        /** QuestionOut */
        QuestionOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Maxchoice */
            maxChoice?: number | null;
            /** Options */
            options?: components["schemas"]["OptionOut"][] | null;
            /** Minlabel */
            minLabel?: string | null;
            /** Maxlabel */
            maxLabel?: string | null;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Step */
            step?: number | null;
            /** Subquestions */
            subQuestions?: components["schemas"]["SubQuestionDef"][] | null;
        };
        /** QuestionWithAnswerOut */
        QuestionWithAnswerOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Maxchoice */
            maxChoice?: number | null;
            /** Options */
            options?: components["schemas"]["OptionOut"][] | null;
            /** Minlabel */
            minLabel?: string | null;
            /** Maxlabel */
            maxLabel?: string | null;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Step */
            step?: number | null;
            /** Subquestions */
            subQuestions?: components["schemas"]["SubQuestionDef"][] | null;
            /** Answer Ids */
            answer_ids?: string[] | null;
            /** Text */
            text?: string | null;
        };
        /** SaveResult */
        SaveResult: {
            /**
             * Status
             * @example success
             */
            status: string;
            /**
             * Saved Count
             * @example 3
             */
            saved_count: number;
        };
        /** ScheduleIn */
        ScheduleIn: {
            /**
             * Meeting Date
             * Format: date
             */
            meeting_date: string;
            /**
             * Meeting Time
             * Format: time
             */
            meeting_time: string;
            /** Meeting Place */
            meeting_place: string;
        };
        /** ScheduleOut */
        ScheduleOut: {
            /**
             * Meeting Date
             * Format: date
             */
            meeting_date: string;
            /**
             * Meeting Time
             * Format: time
             */
            meeting_time: string;
            /** Meeting Place */
            meeting_place: string;
        };
        /**
         * SubQuestionAnswerIn
         * @example {
         *       "sub_question_id": 2,
         *       "text": "내 장점은 …"
         *     }
         */
        SubQuestionAnswerIn: {
            /**
             * Sub Question Id
             * @description 34번 질문 내 서브 id
             */
            sub_question_id: number;
            /**
             * Text
             * @description 입력 텍스트
             */
            text?: string | null;
        };
        /**
         * SubQuestionDef
         * @description group_input(subQuestions) 정의
         */
        SubQuestionDef: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Placeholder */
            placeholder?: string | null;
            /**
             * Required
             * @default false
             */
            required: boolean;
        };
        /** SubQuestionOut */
        SubQuestionOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Placeholder */
            placeholder?: string | null;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /** Text */
            text?: string | null;
        };
        /** ToggleChecklistIn */
        ToggleChecklistIn: {
            /** Item Id */
            item_id: number;
            /** Checked */
            checked: boolean;
        };
        /**
         * TokenOut
         * @example {
         *       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
         *       "refresh_token": "dGhpc19pc19hX3JlZnJlc2hfdG9rZW4..."
         *     }
         */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
        };
        /** UserChecklistStatus */
        UserChecklistStatus: {
            /** Item Id */
            item_id: number;
            /** Checked */
            checked: boolean;
        };
        /** UserProfileOut */
        UserProfileOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Picture */
            picture: string | null;
            profile: components["schemas"]["ProfileInitialOut"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    debug_token_debug_token_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_google_auth_google_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    callback_auth_google_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_token_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_profile_users_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_profile_users_me_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lifestyle_survey_lifestyle_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionWithAnswerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_lifestyle_survey_lifestyle_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChoiceAnswerList"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_identify_survey_identify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionWithAnswerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_identify_survey_identify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChoiceAnswerList"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preference_survey_preference_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionWithAnswerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_preference_survey_preference_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChoiceAnswerList"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_beliefs_survey_beliefs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionWithAnswerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_beliefs_survey_beliefs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChoiceAnswerList"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_group_input_survey_essay_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupInputOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_group_input_survey_essay_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupInputAnswerList"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_questions_partners_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_partners_partners_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_partner_partners_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPartnerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_default_items_checklist_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItemOut"][];
                };
            };
        };
    };
    get_checklist_checklist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserChecklistStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_check_checklist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleChecklistIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_schedules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_schedule_schedules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
